include:
  - .gitlab/ci/*.gitlab-ci.yml

stages:
  - build
  - deploy
  - rollback

build-staging:
  stage: build
  extends: .build_template_staging
  environment:
    name: test
    url: https://test.app.delever.uz
  variables:
    ENV_TAG: test
  only:
    - staging

build-prod:
  stage: build
  extends: .build_template_prod
  environment:
    name: production
    url: https://app.delever.uz
  variables:
    ENV_TAG: latest
  only:
    - master

deploy-staging:
  stage: deploy
  extends: .deploy_template
  environment:
    name: test
    url: https://test.app.delever.uz
  variables:
    NAMESPACE: test
    VALUES_FILE: .helm/values-test.yml
    K8SCONFIGJSON: $DELEVER_NEW_KUBECONFIG
  only:
    - staging

deploy-prod:
  stage: deploy
  extends: .deploy_template
  environment:
    name: production
    url: https://app.delever.uz
  variables:
    NAMESPACE: prod
    VALUES_FILE: .helm/values-prod.yml
    K8SCONFIGJSON: $DELEVER_NEW_KUBECONFIG
  only:
    - master

rollback-staging:
  stage: rollback
  environment:
    name: test
    url: https://test.app.delever.uz
  extends: .rollback_template
  variables:
    NAMESPACE: test
    K8SCONFIGJSON: $DELEVER_NEW_KUBECONFIG
  when: manual

rollback-prod:
  stage: rollback
  environment:
    name: production
    url: https://app.delever.uz
  extends: .rollback_template
  variables:
    NAMESPACE: prod
    K8SCONFIGJSON: $DELEVER_NEW_KUBECONFIG
  when: manual
