FROM node:21-alpine as builder
RUN apk update && apk add yarn git

RUN mkdir app
WORKDIR app

COPY package*.json ./
RUN yarn install


COPY . ./
RUN rm -rf .env.development

RUN yarn build

CMD ["yarn", "start"]

